# Continuous Integration (CI) to build PW.JarVerify
# using the .NET CLI on Azure Pipelines.

# Triggered when pushing to the "master"
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - .gitignore
    - LICENSE
    - NOTES.txt
    - README.md

# Pipeline name
name: PW.JarVerify.CI.$(Build.BuildId)

# Global variables
variables:
  vmImage: windows-2022
  libProjects: |
    **/PW.JarVerify/*.csproj
  buildConfiguration: Release

jobs:
- job: Build
  displayName: Build PW.JarVerify
  pool:
    vmImage: $(vmImage)
  steps:
  # Build and pack PW.JarVerify
  - task: DotNetCoreCLI@2
    displayName: Build PW.JarVerify
    inputs:
      command: custom
      custom: pack
      projects: $(libProjects)
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) -p:CIBuildId=$(Build.BuildId)'
  # Publish to pipeline artifacts
  - task: PublishPipelineArtifact@1
    displayName: Publish library to pipeline artifacts
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: PW.JarVerify
